name: CI

on:
  push:
    paths-ignore:
      - '.dockerignore'
      - '.github/workflow/e2e.yml'
      - '.github/workflow/pkg.yml'
      - '.github/workflow/e2e test cache rebuild.yml'
      - 'Changelog.md'
      - 'Dockerfile'
      - 'doc/**'
      - 'docker/**'
      - 'LICENSE'
      - 'README.md'
      - 'tests/e2e/**'

  # Hmm, annoying, do we really have to duplicate this?
  pull_request:
    paths-ignore:
      - '.dockerignore'
      - '.github/workflow/e2e.yml'
      - '.github/workflow/pkg.yml'
      - '.github/workflow/e2e test cache rebuild.yml'
      - 'Changelog.md'
      - 'Dockerfile'
      - 'doc/**'
      - 'docker/**'
      - 'LICENSE'
      - 'README.md'
      - 'tests/e2e/**'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, 1.43.0, beta]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo build --verbose
    - run: cargo test --verbose 2>&1

  coverage:
    name: coverage
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo install cargo-tarpaulin
    - run: cargo tarpaulin -v -o Html
    - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: tarpaulin-report.html

  allfeatures:
    name: allfeatures
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, 1.43.0, beta]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo build --verbose --all-features
    - run: cargo test --verbose --all-features 2>&1
